# This is a basic workflow to help you get started with Actionsc

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    uses: cpintado-org/reusable/.github/workflows/reusable.yml@main
    with:
      username: "test"
      environ: ${{ github.ref_name }}
      secrets: inherit

  job2:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref_name }}
          echo $TESTSECRET
        env:
          TESTSECRET: ${{ secrets.SEC1 }}
